detect changes

diff --git a/.github/workflows/code-health.yml b/.github/workflows/code-health.yml
--- a/.github/workflows/code-health.yml
+++ b/.github/workflows/code-health.yml
@@ -72,6 +72,17 @@ jobs:
         run: export resource_name=push_based_log_export && make generate-doc
       - name: Doc for search_deployment
         run: export resource_name=search_deployment && make generate-doc
+      - name: Find mutations
+        id: self_mutation
+        run: |-
+          git add .
+          git diff --staged --patch --exit-code > .repo.patch || echo "self_mutation_happened=true" >> "${GITHUB_OUTPUT}"
+      - name: Fail build on mutation
+        if: steps.self_mutation.outputs.self_mutation_happened
+        run: |-
+          echo "::error::Files were changed during build (see build log). If this was triggered from a fork, you will need to update your branch."
+          cat .repo.patch
+          exit 1
   call-acceptance-tests-workflow:
     needs: [build, lint, shellcheck, unit-test, generate-doc]
     secrets: inherit
