detect if generate resource is not up-to-date

diff --git a/.github/workflows/code-health.yml b/.github/workflows/code-health.yml
--- a/.github/workflows/code-health.yml
+++ b/.github/workflows/code-health.yml
@@ -75,12 +75,32 @@ jobs:
         id: self_mutation
         run: |-
           git add .
-          git diff --staged --patch --exit-code > .repo.patch || echo "self_mutation_happened=true" >> "${GITHUB_OUTPUT}"
+          git diff --staged --patch --exit-code > doc.repo.patch || echo "self_mutation_happened=true" >> "${GITHUB_OUTPUT}"
       - name: Fail build on mutation
         if: steps.self_mutation.outputs.self_mutation_happened
         run: |-
           echo "::error::Files were changed during build (see build log). If this was triggered from a fork, you will need to update your branch."
-          cat .repo.patch
+          cat doc.repo.patch
+          exit 1
+  generate-resource-check:
+    runs-on: ubuntu-latest
+    permissions: {}
+    steps:
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
+      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b
+        with:
+          go-version-file: 'go.mod'
+      - run: make generate-resource
+      - name: Find mutations
+        id: self_mutation
+        run: |-
+          git add .
+          git diff --staged --patch --exit-code > resource.repo.patch || echo "self_mutation_happened=true" >> "${GITHUB_OUTPUT}"
+      - name: Fail build on mutation
+        if: steps.self_mutation.outputs.self_mutation_happened
+        run: |-
+          echo "::error::Files were changed during build (see build log). If this was triggered from a fork, you will need to update your branch."
+          cat resource.repo.patch
           exit 1
   call-acceptance-tests-workflow:
     needs: [build, lint, shellcheck, unit-test, generate-doc-check]
